### ISSUE TITLE
The examine indexer only indexes 100 products

### ISSUE THREAD

**Issue by chris64digital** [Merchello/Merchello#1171]
I have had an issue recently where I have had to reindex my products and have found that the examine manager only ever shows 100 products in the index. Adding/editing products adds them to the index but since I have over 3000 products this is not realistic to have to do. I am relying on the index for product searching on my site.

**Comment by protherj** [comment]
I'll let Rusty have the final word, but the way the custom Merchello Examine Indexer works is that it pre-fills the index for the first 100 (# may be configurable).  Then when a product is requested it checks the index first, if it doesn't find it then it pulls it from the DB, then it inserts it into the Examine index and returns it.

Its basically used more as a cache than a true Examine search index.

It may be possible to configure that behavior or create a new index for searching and leave the current index as is.  However, I'd have to defer that to Rusty who built the index.

Thanks,
Jason

**Comment by rustyswayne** [comment]
Jason's correct that we are using it as a cache ATM.  I've been using Umbraco's ExternalIndexer for searching.  

The index will rebuild itself -  basically what we are doing is performing paged dB queries that return the product key.  We then check the index to see if we get a match, if we do, we return the result, if not we query the entire product graph pass it to examine to be reindexed and return.
