### ISSUE TITLE
Crash when local decimal are not the "." in the basket item price

### ISSUE THREAD

**Issue by pdsavard** [Merchello/Merchello#1251]
We just need to add this line 
decimal converted = decimal.TryParse(dictionary[Constants.ExtendedDataKeys.Price], System.Globalization.NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out converted) ? converted : 0;

then in the GetLineItemCollection<T>() in ExtendedDataExtensions.cs

Final result of woking function:
        public static LineItemCollection GetLineItemCollection<T>(this ExtendedDataCollection extendedData) where T : LineItemBase
        {
            if (!extendedData.ContainsKey(Constants.ExtendedDataKeys.LineItemCollection)) return null;

            var xdoc = XDocument.Parse(extendedData.GetValue(Constants.ExtendedDataKeys.LineItemCollection));
            var lineItemCollection = new LineItemCollection();
            foreach (var element in xdoc.Descendants(Constants.ExtendedDataKeys.LineItem))
            {
                
                var dictionary = GetLineItemXmlValues(element.ToString());

                var extendData = new ExtendedDataCollection(dictionary[Constants.ExtendedDataKeys.ExtendedData]);

                decimal converted = decimal.TryParse(dictionary[Constants.ExtendedDataKeys.Price], System.Globalization.NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out converted) ? converted : 0;

                var ctrValues = new object[]
                    {                        
                        new Guid(dictionary[Constants.ExtendedDataKeys.LineItemTfKey]),
                        dictionary[Constants.ExtendedDataKeys.Name],
                        dictionary[Constants.ExtendedDataKeys.Sku],
                        int.Parse(dictionary[Constants.ExtendedDataKeys.Quantity]),
                        converted,
                        new ExtendedDataCollection(dictionary[Constants.ExtendedDataKeys.ExtendedData])
                    };
                               
                var attempt = ActivatorHelper.CreateInstance<LineItemBase>(typeof(T).FullName, ctrValues);

                if (!attempt.Success)
                {
                    LogHelper.Error<LineItemCollection>("Failed to instantiate a LineItemCollection from ExtendedData", attempt.Exception);
                    throw attempt.Exception;
                }
                
                attempt.Result.ContainerKey = new Guid(dictionary[Constants.ExtendedDataKeys.ContainerKey]);

                lineItemCollection.Add(attempt.Result);
            }

            return lineItemCollection;
        }

**Comment by rustyswayne** [comment]
@pdsavard Man I'm so sorry I missed this.  Not used to checking here for issues =)

I'll flag it and create an issue on issues.merchello.com so we can have something to track against.

**Comment by rustyswayne** [comment]
http://issues.merchello.com/youtrack/issue/M-707
