### ISSUE TITLE
Server Error / at website startup

### ISSUE THREAD

**Issue by biapar** [Merchello/Merchello#1294]
I've build the source solution version 1.9 and started Merchello.Web.UI

Which is the Umbraco Backend Password?
The website give this error:

Errore server nell'applicazione '/'.

Impossibile trovare il percorso di rete
( network path error )

**Comment by rustyswayne** [comment]
Yeah, in the 1.9.0 branch I have the connection string pointed at a local SQL server as I'm adding a couple of database tables and was finding it a pain in the rump to merge in the SQLCE stuff while I'm testing the migration (upgrade path) and the installs.  

You can change the connection string back to use the SQLCE db, should work fine.

U: admin
P: 1234

**Comment by biapar** [comment]
Changed and works.

  <connectionStrings>
    <remove name="umbracoDbDSN" />
    <add name="umbracoDbDSN" connectionString="Data Source=|DataDirectory|\Umbraco.sdf;Flush Interval=1;" providerName="System.Data.SqlServerCe.4.0" />
    
    
  </connectionStrings>
