### ISSUE TITLE
"MerchStore" ContentTypeAlias

### ISSUE THREAD

**Issue by psot** [Merchello/Merchello#1324]
Are the "MerchStore" and "MerchCheckout" ContentTypeAlias in RenderControllerBase and SurfaceControllerBase forgotten or something? They don't seem to be used anywhere in Bazaar because we have this info in the model.

**Comment by rustyswayne** [comment]
Those were old ContentTypeAlias from the original Kitten example site.  Are you seeing them in the Bazaar?

**Comment by psot** [comment]
Rusty, yes these aliases are present as properties in both RenderControllerBase and SurfaceControllerBase. They're not used, but I guess they add a small overhead to performance. I was just trying to figure out why were they present, I hadn't seen at all the Kitten example site.

**Comment by rustyswayne** [comment]
Probably a remnant from a copy paste ... thanks for the heads up.

**Comment by rustyswayne** [comment]
I removed these.  Thanks again.
