### ISSUE TITLE
How to customize basket cart, checkout and payment?

### ISSUE THREAD

**Issue by biapar** [Merchello/Merchello#1336]
Hi,

I need to customize the cart, checkout and payment. 
I need to customize cart because I've to add only one product and one quantity and checkout because I need to add some info. 
Payment because I need to create a subscription.

Is't better to start from Bazar or install only Merchello and build cart as write here http://merchello.com/documentation/getting-started/how-to/Build-The-Basket?

How to customize if I start from Bazar?

**Comment by rustyswayne** [comment]
Subscriptions would be done via a Payment Provider and generally sort of handled in reverse of a normal checkout.  What I mean by this is, the payment provider processes the payment on a schedule and generally has some sort of notification (like a webhook) which you would subscribe to and generate an invoice based off the notification.

The initial checkout is generally setting up the subscription with the payment provider and really nothing to do with Merchello (other than working the payment provider).

I think this is a good conversation for the forum.
