### ISSUE TITLE
Method of payment drilldown: not populated with Paypal

### ISSUE THREAD

**Issue by biapar** [Merchello/Merchello#1344]
Hi,

I've installed and configured Paypal 1.0.4 and Merchello 1.9.x. Why is there not Paypal into the drilldown?

**Comment by biapar** [comment]
I found why.
Because:

  PaymentMethods = (viewModel.ResolvePaymentForms
                     ? allowedMethods.Where(x => paymentInfoArray.Any(y => y.PaymentMethodKey == x.PaymentMethod.Key && y.UrlActionParams != null))
                     : paymentMethodsArray)
                     .Select(x => new SelectListItem() { Value = x.PaymentMethod.Key.ToString(), Text = x.PaymentMethod.Name }),

                PaymentMethodUiInfo = viewModel.ResolvePaymentForms ? 
                            paymentInfoArray.Where(x => x.UrlActionParams != null) :
                            paymentInfoArray,

**Comment by rustyswayne** [comment]
The Bazaar resolver requires that the plugin provider include a controller that can be resolved by a form.  You can look at the Cash provider to see how that's done by inheriting from a base and including an attribute.  I don't think the Scandia guys have done this for the PayPal plugin.
