### ISSUE TITLE
Billing and Shipping address empty

### ISSUE THREAD

**Issue by biapar** [Merchello/Merchello#1345]
Hi,

I try to create an order. From customer private area, I see the addresses, but not from backoffice.  I try to save an addresses before the new order, but after a new order was empty.

**Comment by rustyswayne** [comment]
@biapar We need to keep these sorts of issues in http://issues.merchello.com - it's difficult to keep up with things in too many places =)

I think someone else found an indexing issue with the ICustomer .SaveCustomerAddress( ...) extension method.  Is this what you are using?

If so, if you rebuild your customer index (Examine) do you see the address in the back office?

**Comment by biapar** [comment]
Hi, I rebuild all index and the addresses are ok. Why this bug?

**Comment by rustyswayne** [comment]
http://issues.merchello.com/youtrack/issue/M-750
