### ISSUE TITLE
Issue capturePayment() not working in backend

### ISSUE THREAD

**Issue by biapar** [Merchello/Merchello#1346]
Could you read my analisys?

https://our.umbraco.org/projects/collaboration/merchello/merchello/66510-capturepayment-not-working-in-backend

**Comment by rustyswayne** [comment]
Replied.

**Comment by biapar** [comment]
Hi, so

1) Check that Paypal plugin is able to receipt capture from Paypal backoffice. How and where to save Paypal token or other info for finding order and match it to operate with Paypal IPN?

2) Which is the url that need to point after authorized? 

3) How to manually change the state into Merchello backoffice?

4) Why Do not work capture for standard cash payment?

**Comment by biapar** [comment]
I've update the problem. The balance into the invoice is zero. Why?

https://our.umbraco.org/projects/collaboration/merchello/merchello/66510-capturepayment-not-working-in-backend
