### ISSUE TITLE
Issue: Cash payment: balance is zero. Why?

### ISSUE THREAD

**Issue by biapar** [Merchello/Merchello#1352]
Hi,

I see a bug ( the same with Paypal payment ) into Merchello. I try to use cash payment, but Merchello report balance zero and zero into the list of invoices. Why?
Where is assigned the value?

![catturap](https://cloud.githubusercontent.com/assets/661517/8723592/3665fc94-2bcf-11e5-9c1f-c01a3395d3cb.PNG)

**Comment by fspezi** [comment]
Can you try to compile a basket with integer prices only?
I think that it will be works properly.

**Comment by biapar** [comment]
You are right!!!
Why don't work with decimal? Is't a gateway or merchello problem? I think merchello, because don't work for cash payment, too!

**Comment by fspezi** [comment]
No, the issue is in Examine, or better in Lucene.NET.

I solved the issue in my local website, then I pull the patch: https://github.com/Shazwazza/Examine/pull/26

**Comment by biapar** [comment]
How solve? So, it's an Umbraco issue?

**Comment by fspezi** [comment]
Merchello index invoice with Examine. But this operation fails when there is a not-integer value because "I think that" there is a bug in Lucene.NET.  
I found a solution to solve the issue. There is an open patch. Look the link above.

**Comment by biapar** [comment]
How to add that patch?

**Comment by biapar** [comment]
Read here http://issues.merchello.com/youtrack/issue/M-284

**Comment by biapar** [comment]
Solved as I describe here:
our.umbraco.org/projects/collaboration/merchello/merchello/66510-capturepayment-not-working-in-backend#224839
