### ISSUE TITLE
Issue: A foreign key value cannot be inserted because a corresponding primary key value does not exist

### ISSUE THREAD

**Issue by biapar** [Merchello/Merchello#1358]
A foreign key value cannot be inserted because a corresponding primary key value does not exist. [ Foreign key constraint name = FKmerchItemCacheItemmerchItemCache ]

Line 110: var dto = factory.BuildDto(entity); Line 111: Line 112: Database.Insert(dto); Line 113: Line 114: entity.Key = dto.Key;

Source File: c:_Source\CittdelSole\Merchello.Core\Persistence\Repositories\ItemCacheLineItemRepository.cs Line: 112

**Comment by rustyswayne** [comment]
When do you see this occurring?  This infers a record does not exist in the merchItemCache table before the line item is inserted ...

**Comment by biapar** [comment]
It happen sometime when you go to basket. I try again if I'm able to repeat the error.

**Comment by biapar** [comment]
Tried again. If you go to payment gateway and return on this page the basket seem full, but the cache is empty.

**Comment by rustyswayne** [comment]
Is this with the PayPal payment provider?

**Comment by robgha01** [comment]
Im having the same problem but i get this error when i perform a checkout using paypal.
I dide not get this error while developing but now i get it both live and in dev...

Tried to delete the cache by doing var basketCache = MerchelloServices.ItemCacheService.GetItemCacheByCustomer(CurrentCustomer, ItemCacheType.Basket);
            MerchelloServices.ItemCacheService.Delete(basketCache);

still not working the only think i can think of is that i removed the lucine index temp folder and restarted the server maybe the cache could not rebuild ?

**Comment by robgha01** [comment]
When temp is removed cache is empty, rebuilding cache in backoffice then the prices shows correct for products but adding a product to basket results in a produkt with 0 cost and when i try to remove it its still there...

**Comment by robgha01** [comment]
Ok i had to go into the product and resave it... this is a major bugg the cache is not optimal if one has to go throw all products and resave them ?

**Comment by rustyswayne** [comment]
@robgha01 Are you just trying to clear the basket?  There are quite a few layers here ... have you tried Basket.Empty()?

**Comment by robgha01** [comment]
Im talking to my webhost thay are looking at it, i think its someting to do with how thay set the servers and if thats true then its a server setup problem and not a merchello problem. :)

**Comment by biapar** [comment]
Uhm.. I don't think so, but ok to have a new info.

Bp

**Comment by biapar** [comment]
see additional information https://our.umbraco.org/projects/collaboration/merchello/merchello/73183-basket-insert-error-when-click-on-confirm-checkout-help

**Comment by leen3o** [comment]
Closing as this was an AntiVirus issue
