### ISSUE TITLE
Parsing price throws Invalid Format because of culture

### ISSUE THREAD

**Issue by robgha01** [Merchello/Merchello#1444]
in LineItemBase the price is saved as writer.WriteElementString(Constants.ExtendedDataKeys.Price, Price.ToString(CultureInfo.InvariantCulture));

with the invariantCulture when its parsed in ExtendedDataExtensions no culture is specified meaning it will take the current thred culture and parse with that in my case that is sv-SE and the price it tries to parse is 89.000 in my language we dont use dot for seperation we use decimal "," is it possible to change this to get the currency culture of the current price or someting and pass that in to avoid this kind of problems ?

**Comment by tvanro** [comment]
I encountered the same culture/parse issue for SalesPrice and Weight and I fixed it with this pull request: https://github.com/Merchello/Merchello/pull/1442

However... I had no issues with the normal price so maybe it's still something else....

**Comment by robgha01** [comment]
ok, well the strange thing is its not always throwing the exeption but i narrowed it down the the culture part maybe we can fix this by setting invariantCulture on both:
int.Parse(dictionary[Constants.ExtendedDataKeys.Quantity], NumberStyles.Any, CultureInfo.InvariantCulture),
                        decimal.Parse(dictionary[Constants.ExtendedDataKeys.Price], NumberStyles.Any, CultureInfo.InvariantCulture),

**Comment by leen3o** [comment]
Closing as no more information, assume @tvanro pull request fixed the issue.
