### ISSUE TITLE
Changing from Image Cropper to Media Picker in BazaarProductContent Document Type

### ISSUE THREAD

**Issue by marcioduarte89** [Merchello/Merchello#1466]
When in the Bazaar Store (1.12.0) i change the property "Image" in the BazaarProductContent from a Image Cropper to a Media Picker (i wanted to insert images from the media, instead of uploading them from the file system) in the Products -> Extended Content -> Image shows empty (without any content) and i cannot upload image neither from media or file system.

**Comment by rustyswayne** [comment]
I just tried using a media picker through the back office and it worked.  Can you confirm this part is working for you?

You will have to make some changes in the view to display it correctly.  One approach is to use the CorePropertyValueConverters project which would return IPublishedContent for the media item ...
