### ISSUE TITLE
Merchello .control-label css overides all even outside merchello

### ISSUE THREAD

**Issue by robgha01** [Merchello/Merchello#1470]
Hey :)

I debugged a strange problem, all labels in LeBlender and i guess all other who use the class .control-label lived there own life, i found out that a css is loaded into umbraco main frame merchello.css with the class and that it overrides the default umbraco css for labels look on the image to see the problem :D
![merchello eating labels](https://cloud.githubusercontent.com/assets/362726/10547508/3d135cae-7435-11e5-8f39-718f34aa7661.PNG)

if i disable this class it looks normal like this:
![merchello normal labels](https://cloud.githubusercontent.com/assets/362726/10547540/6bc85bd0-7435-11e5-857c-810687bdb769.PNG)

**Comment by robgha01** [comment]
I found one place where this was used i dont know if there is any more places ?
the modification i dide was this add a class to wrapp merchello css rule so it wont trigger on all but merchello html ex:
.merchello-wrapper .control-label {
  width: 160px;
  position: absolute; }

in the following file: filterinvoices.tpl.html line 1 added the class "merchello-wrapper" <div class="merchello-wrapper row-fluid">

now the problem is solved however im still unsure what kind of behavior this change has as im not familar with the backend-css of merchello.

**Comment by rustyswayne** [comment]
@robgha01 I don't think anybody is is that familiar with the backend-css of merchello anymore =)  The offending line is probably something I added to get around a problem I was having so your solution is perfect.

**Comment by robgha01** [comment]
@rustyswayne ok :)

**Comment by joelbhansen** [comment]
This should be fixed in https://github.com/Merchello/Merchello/pull/1482
