### ISSUE TITLE
Merchello extended content view editorState.current is null for any custom editor

### ISSUE THREAD

**Issue by robgha01** [Merchello/Merchello#1471]
Hi im using uSeoPro (https://our.umbraco.org/projects/developer-tools/useo-pro/)
and im getting errors in a extended product content context the editorState is not set.

This editor works outside of merchello extended content.

**Comment by rustyswayne** [comment]
@robgha01 I've never used that plugin before, but it may require the content have a content id or maybe recursive properties?

**Comment by robgha01** [comment]
Um, well i looked at the code of the plugin it uses someting like that "contentEditingHelper.getAllProps(editorState.current);" to get all properties of the content.

however when i debug editorState.current is null resulting in a exeption.
its also used to get a part of the url it seams "editorState.current.urls[0];"

**Comment by rustyswayne** [comment]
@robgha01 I looked this and Merchello does not use the Umbraco's editorState.  Looking at the angular a bit more closely, I don't think it'll work very well (if at all) with Merchello's extended content as it does not actually exist in the content tree.

Do you know where in the useo-pro plugin the method is being used?

**Comment by robgha01** [comment]
@rustyswayne its used in uSeoProController.controller.js lines:
8: var url = editorState.current.urls[0];
15: $scope.pageName = editorState.current.name;
97: var allProps = contentEditingHelper.getAllProps(editorState.current);
