### ISSUE TITLE
merchello.bazaar.js toggleBillingIsShipping $('#billing-is-shipping').checked is undefined in chrome Version 46.0.2490.71 m

### ISSUE THREAD

**Issue by robgha01** [Merchello/Merchello#1474]
Hey @rustyswayne 

I found out that my shipping checkbox is not working i dont know if anyting is changed from older verisions regarding this method or if the latest update of chrome (possible more browsers) made this broken. according to this stackoverflow post http://stackoverflow.com/questions/6528156/jquery-attr-method-returns-undefined-for-a-checked-checkbox its becuse of the use of ' insteed of " thay recomended to do $('#checkbox1').prop('checked') - jQuery 1.6+ faster or $('#checkbox1').is(':checked') - all jQuery versions, but slower.

it works if i change line: 405 to $('#shipping-address').toggle(!$('#billing-is-shipping').prop('checked'));

**Comment by biapar** [comment]
($('#billing-is-shipping').is(':checked'))
