### ISSUE TITLE
CurrentCustomer is different every time i initialize due to "compatibilityMode" in <machineKey> (web.config)

### ISSUE THREAD

**Issue by jessetinell** [Merchello/Merchello#1483]
**Short intro**:
My application (Umbraco, .net 4.5) uses shared authentication with another (older) webforms-application (.net 4.0).
I need to use a Machine key with attribute "compatibilityMode=Framework20SP2" for this to work correctly. 

**BUT**:
With that attribute Merchello stops working.

CurrentCustomer is.. different everytime its initialized in the MerchelloSurface-constructor.
For example: I can add stuff to the Basket, but when I reload the page I become a new customer (key is changed) and basket is empty.
`var customerContext = new CustomerContext(UmbracoContext);`
`_currentCustomer = customerContext.CurrentCustomer;`

I use the same MerchelloSurfaceController as in their [samples](https://github.com/Merchello/Samples/blob/master/Samples/How-To-Articles/Basket/UmbracoCms/App_Code/Controllers/MerchelloSurfaceController.cs).

Any ideas?

**Comment by rustyswayne** [comment]
My guess is the Umbraco Membership provider is using a different "application" in the .NET user provider than the older application similar to the way Umbraco separates Members and Users.

A quick solution would be to write your own `CustomerContext` inheriting from `Merchello.Web.Pluggable.CustomerContextBase`

In your class you to need to override 3 methods that are usually really quick to write:

`````csharp

        /// <summary>
        /// Returns true or false indicating whether or not the current membership user is logged in.
        /// </summary>
        /// <returns>
        /// The <see cref="bool"/> indicating whether the current user is logged in.
        /// </returns>
        protected abstract bool GetIsCurrentlyLoggedIn();

        /// <summary>
        /// Gets the member/user login or user name used to sign in
        /// </summary>
        /// <returns>
        /// The <see cref="string"/>.
        /// </returns>
        /// <remarks>
        /// Merchello makes the association between membership provider users and Merchello customers by username
        /// </remarks>
        protected abstract string GetMembershipProviderUserName();

        /// <summary>
        /// Gets the unique ID from the Membership Provider
        /// </summary>
        /// <returns>
        /// The ID or key from the Membership provider as a string value 
        /// </returns>
        protected abstract string GetMembershipProviderKey();

`````

The last thing that needs to happen is to let Merchello know about the switch, so go to the `~/App_Plugins/Merchello/config/merchello.config` file and find

`````xml
  <pluggable>
    <object alias="CustomerContext" type="Merchello.Web.CustomerContext, Merchello.Web" />
  </pluggable>
`````

and change the type reference to your new class.  

I think that will do the trick.
