### ISSUE TITLE
Product variants: Extended content but no url

### ISSUE THREAD

**Issue by robgha01** [Merchello/Merchello#1486]
Hey,

I find it strange that a product variant has a extended content but no url is this a todo or just someting missing or am i confusing things up ?

if there is supposed to be a url for them will thay be created under the product itself so its webiste.com/productslope/variantslope ?

Regards
Robert

**Comment by rustyswayne** [comment]
I actually went back and forth with that with several people and it was ultimately decided that in most cases sites would not implement individual pages for variants of a product.  Database wise the slug can be saved.  

Do you have a use case for when this should happen.  It would make a good conversation in the Our forum.

**Comment by robgha01** [comment]
Well what i was trying to do and have done is a presentation of products and there variants however i cant have a read more link to a variant as it has no slug.

i dont know if i think correct but if i have variants for a product i see the main product as a abstraction to the variants as there is no option to select the main product when one view the product page and want to add it to the basket.

as of a user case its complicated question its good to have a slug if the variant needs different or specific information one may want to have different image for sizes of a bottle as a example but at the same time if the information is to close to the main product it will then create duplicate content and that is not viable.

**Comment by rustyswayne** [comment]
The IProductContent as has collection of IProductVariantContent which could be found either by SKU or selected option choices (which is how I've done it before).  When the user selects options that define a variant, you can pull the IProductVaraintContent properties for images ...

**Comment by robgha01** [comment]
i see, well it was a bit confusing and some things still are but its not unexpected as the project is still in movement :)

im going to change some stuff and see what i can do with the new view. anyway one thing about the variant when i iterated the variant and called content.Url it was empty well it dide not point to anything it may be good to point it against the IProductContents url property or something its not a major thing but can be a little confusing.

thanks for answering so fast ^^

**Comment by rustyswayne** [comment]
@robgha01 I'd love to be able to simplify / standardize on a the virtual content API.  I'd love to see any extension methods you come up with during your build process.  I'm trying to collect these from people to get an idea of what needs to be offered in the Core.  I held off on adding things like that immediately to avoid having an entire API that would quickly become obsoleted ... sort of a chicken and the egg thing.

**Comment by robgha01** [comment]
yea, that is good. i dont know if you are familiar with episerver i have worked with it before and there api has this problem its even worsh as thay have diffrent metods that do the same but for diffrent verisions in one same place so i know how complicated it can be for the user if that would happen and that in my opinion is not what umbraco stands for and not merchello etcher. :)

Im happy to help out and improve the project as i have showed before and will report anything that i find is simplifying and helping.
