### ISSUE TITLE
Controller name conflict

### ISSUE THREAD

**Issue by konius** [Merchello/Merchello#1514]
Just found out that settingsResource controller conflicts with Analytics package leaving Analytics UI broken.

I've replaced all references in /App_plugins/Analytics to AnalyticsSettingsResource and it started working again, but something to highlight for future updates using more specific names for Merchello to avoid conflicts.

**Comment by rustyswayne** [comment]
@konius Good to know, thanks.  

Out of curiosity, how is the Analytics settingsResource being register into the "umbraco" application?  Merchello has everything being loaded into it's own module which is then pushed into the "umbraco.plugins" module.  So a conflict could occur if the Analytics settingsResource is pushed directly into the umbraco applcation.  If it had it's own module, which was pushed into the "umbraco.plugins" module the two should be isolated.

**Comment by konius** [comment]
@rustyswayne I wouldn't know how to answer your questions as I had to get help solving the controller issue in the forum. 

I've posted this on Analytics repo as well:
https://github.com/warrenbuckley/Analytics/issues/44#issuecomment-165470089

**Comment by leen3o** [comment]
Closing this as Warren is changing the Analytics plugin
