### ISSUE TITLE
Which version of Umbraco and Merchello work perfectly together ?

### ISSUE THREAD

**Issue by sonphnt** [Merchello/Merchello#1534]
As the header. I want to know Which version of Umbraco and Merchello work perfectly together including Bazaar store example ? Thanks

**Comment by leen3o** [comment]
The latest version of Merchello v1.13.3 works with the latest Umbraco v7.3.4

https://our.umbraco.org/projects/collaboration/merchello/

**Comment by sonphnt** [comment]
Hi leen3o,

I follow your instruction but when I install Bazzar.StoreOnly.1.13.3. I got this message
"Object reference not set to an instance of an object."

Do you know the reason ?

Thanks

**Comment by leen3o** [comment]
Did you install Merchello v1.13.3 first?

**Comment by sonphnt** [comment]
Hi leen3o,

I did install Merchello 1.13.3. And then install Bazaar.StoreOnly 1.13.3. Do you think I should install "Merchello.Bazaar.CombinedInstall_1.13.3" before I install StoreOnly 1.13.3.

Thanks

**Comment by rustyswayne** [comment]
Checkout https://our.umbraco.org/projects/collaboration/merchello/merchello/67963-error-merchellocontext-null#comment-237775
