### ISSUE TITLE
Do we have plan with DIBS payment ?

### ISSUE THREAD

**Issue by sonphnt** [Merchello/Merchello#1537]
Hi everyone,

I see we are supporting some payment gateway but does not have DIBS. I just want to know do we have plan for this ?

Thanks

**Comment by leen3o** [comment]
Sorry I have never heard of that gateway. It won't be something we'll be adding anytime soon, but please feel free to develop it yourself? There are already several examples in the core you can follow/use.

https://github.com/Merchello/Merchello/tree/merchello-dev/Plugin/Payments

We are always looking for the community to help us by creating payment gateways.
