### ISSUE TITLE
Braintree Provider Settings - Envrionment Type Bug

### ISSUE THREAD

**Issue by charlie-haley** [Merchello/Merchello#2013]
Hello,

I've noticed a fairly serious issue that prevents payments being processed via Braintree on production. I see there's two variables for environment being set when saving the provider settings. Here's a JSON snippet on what gets posted on our production envrionment when I click save

`{  
   "environment":"Production",
   "publicKey":"xxxxxxxxxxxxxxxxxx",
   "privateKey":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "merchantId":"xxxxxxxxxxxxxxxxxx",
   "merchantDescriptor":{  
      "name":null,
      "url":null,
      "phone":null
   },
   "defaultTransactionOption":"SubmitForSettlement",
   "environmentType":"Sandbox"
}`

Notice that environment and environmentType are not the same and that it's forced to Sandbox despite the dropdown being set to "Production". I've temporarily got around this by setting environmentType to be the same value as environment in the angular controller.

Obviously it's not a permanent fix and may be worth taking a deeper look into.

Thanks,
Charlie

**Comment by YodasMyDad** [comment]
Thanks for reporting this. I'll look into it.

**Comment by YodasMyDad** [comment]
Fixed https://github.com/Merchello/Merchello/pull/2015
