### ISSUE TITLE
WARN: Merchello.Web.Caching.VirtualContentCache: Could not map all items to virtual content

### ISSUE THREAD

**Issue by tjanela** [Merchello/Merchello#2016]
Hey @rustyswayne, opening an issue here regarding a report originally posted [here](https://our.umbraco.org/projects/collaboration/merchello/merchello/81924-could-not-map-all-items-to-virtual-content).

Possible [offending line](https://github.com/Merchello/Merchello/blob/7b73fbca363dbd9d45f12d8442985ac0bf5c73b8/src/Merchello.Web/Caching/VirtualContentCache%7BT%7D.cs#L151).

Seeking clarification on why we are comparing 
`items.Count() != page.ItemsPerPage`

Since this will most likely evaluate to false when using:
`Merchello.Query.Product.TypedProductContentFromCollection(Guid.Parse("a0f663f6-516b-465b-b70e-7de7bcf897b0"));`

**Comment by YodasMyDad** [comment]
Hmmm I think it's just an oversight and needs removing.

**Comment by YodasMyDad** [comment]
Have created a pull request. I think it's just supposed to check it still has the same amount in the original list after mapping. 

https://github.com/Merchello/Merchello/pull/2017
