### ISSUE TITLE
Angular UI issue

### ISSUE THREAD

**Issue by Jemzz** [Merchello/Merchello#2018]
Broken merchello backoffice when trying to save a new customer and tax for everywhere else. Unable to edit and save existing customer address and retrieve address. Getting error message "Form submission cancelled because the form is not connected" on console whilst using chrome and getting "document.getElementById() must have a value" on firefox. Installed a brand new instance of merchello with fast track and the result is still the same

![capurtgure](https://user-images.githubusercontent.com/12433303/30487107-591e4c98-9a2a-11e7-808f-9327c898eb9f.PNG)

**Comment by YodasMyDad** [comment]
Pretty certain this was fixed in the upcoming version next week. I'll close for now, but after release if you still have an issue we can re-open it.

**Comment by Jemzz** [comment]
@YodasMyDad when will be the next release?
