### ISSUE TITLE
Unable to install with Umbraco 7.7.1

### ISSUE THREAD

**Issue by jamescutts** [Merchello/Merchello#2028]
Installation of Merchello 2.5 fails (using local install via zip) on umbraco 7.7.1.

This then also stops umbraco starting up correctly.

**Comment by jamescutts** [comment]
Just noticed there seems to be a pull request open for this

**Comment by rustyswayne** [comment]
@jamescutts Yep - just finished up getting the FastTrack starter installing as well.  We should have version 2.6.0 out in a few days.
