### ISSUE TITLE
Broken example of how to create dynamic collections

### ISSUE THREAD

**Issue by SteveEdson** [Merchello/Merchello#2032]
I'm trying to create a dynamic sales collection of `all invoices which contain a line item with a specific sku`. The docs at https://merchello.readme.io/docs/sales-collections provide an example of how to do this

> Below is the code for the Unpaid Invoices dynamic collection, which you can use as a reference to create your own

However, the important part:

```c#
var query = Query<IInvoice>.Builder.Where(x => x.InvoiceStatusKey == Constants.DefaultKeys.InvoiceStatus.Unpaid);

return _invoiceService.GetPagedKeys(query, page, itemsPerPage, sortBy, sortDirection);
```

Isn't possible, as `_invoiceService.GetPagedKeys` is an internal method. Can this be changed to public / is there a way around this?

Thanks.

**Comment by YodasMyDad** [comment]
Ah. I'll speak with Rusty but I don't see why that is internal.

**Comment by SteveEdson** [comment]
Awesome, thanks!
