### ISSUE TITLE
Product details page the site looks empty.

### ISSUE THREAD

**Issue by mothman1** [Merchello/Merchello#2037]
When open a product page I lose all site menu and images, just like the site has no other pages. See attached screenshots (products list, and product details). What wrong am I doing?

![1](https://user-images.githubusercontent.com/1375606/31287247-8a8929d0-aab8-11e7-80b9-800fbb0287cf.jpg)
![2](https://user-images.githubusercontent.com/1375606/31287246-8a750e14-aab8-11e7-9973-17f0a5aec60a.jpg)

**Comment by YodasMyDad** [comment]
Please post in the umbraco forums.
