### ISSUE TITLE
Product list in admin area returns too much data

### ISSUE THREAD

**Issue by cwjackso** [Merchello/Merchello#2042]
Seems to be a bug with the admin api controller which is returning way too much data for a simple product view.

See the below image from chrome's network panel

![image](https://user-images.githubusercontent.com/12407694/31452970-56de08f0-aea8-11e7-95ae-1134e4785db7.png)

We have a lot of variants per product, but there is no reason we can see for these to be returned in a list view of products.

Carl

**Comment by YodasMyDad** [comment]
It returns them as in the product list, it shows the price to and from of the variants. The query needs to be optimised to just find the to and from price for the variants and return just the product. Not get all variants for all products.

**Comment by cwjackso** [comment]
@YodasMyDad NOt sure if you noticed but the recently viewed products has the same issue - should be an easy fix now this is done.

Thanks
