### ISSUE TITLE
Multi store

### ISSUE THREAD

**Issue by mothman1** [Merchello/Merchello#2044]
Is multi store possible in Merchello?

I have one umbraco and multi stores (all for one company). The company have different products for each store but wishes to allow a customer to purchase products from any of the stores and check them out in one go.

The hosting structure is as follows:
storeA.company.com  and contains storeA products
storeB.company.com  and contains storeB products

The issues i'm currently having are:
1. The product page is virtual, hence ID is 0 and when using GetStoreRoot() method I get the top store all the time - which is incorrect for products in other stores. How can I get the actual product store root?

2. When adding a product from store A to cart and another from store B, I only see one of the two added products in the cart page of the related store - How can I merge all stores cart and checkout pages?

Please advise.

**Comment by SteveEdson** [comment]
If you're still wanting to use a single basket between all stores, can't each 'store' just have a picker for one or more product collection, and only show those products within its store? Each store could be represented by an Umbraco document type, with the picker for the collections.

**Comment by mothman1** [comment]
Thanks Steve,

Sure, I'm using different products collection for each store, and don't have a problem displaying the products list of each relevant store. However, the issue appears when you click to view a product details. In Merchello you use VirtualContent for product details page which is why the product page won't have content id, hence you cannot find its actual parent (the relevant store).

**Comment by SteveEdson** [comment]
I guess you could also create your own document type for a product, and then use a render controller to pull through the product data. You could set a URL with `/{storeId/products/{productId}` and be able to get the info you need that way. But yeah, it'd be interesting to see this baked in as a standard feature.

**Comment by YodasMyDad** [comment]
Sort of is the best answer. It would take a bit of work. This is something that is going to be built into v4 of Merchello.

**Comment by YodasMyDad** [comment]
Can you please move this question to our.umbraco forums too.

**Comment by EnterpriseWide** [comment]
Is multi tenant support a feature on the road map for v4 as well?
