### ISSUE TITLE
Merchello Customer Primary address

### ISSUE THREAD

**Issue by 2014amja** [Merchello/Merchello#2050]
The billing address is set and marked as "Primary address". This will get the address to be prefilled for the costumer.

But it only works once. When the order is placed the address is no longer marked as primary.

So the next time the costumer adds stuff to the basket, the customer will not get any address.
See more: 
![primary address](https://user-images.githubusercontent.com/10165132/31540689-97944d40-b00c-11e7-9c93-6e77a7a0271b.png)

https://our.umbraco.org/projects/collaboration/merchello/merchello//88655-merchello-customer-primary-address

**Comment by YodasMyDad** [comment]
This was just a caching issue. Resolved in 2.7.0
