### ISSUE TITLE
Tax not calculated properly on product total

### ISSUE THREAD

**Issue by Jemzz** [Merchello/Merchello#2054]
When calculating product total with taxed value, pennies are left off the total

one quantity
![capture](https://user-images.githubusercontent.com/12433303/31548236-1a7769e4-b022-11e7-86e0-4c9417f485d2.PNG)

two quantities
![capture](https://user-images.githubusercontent.com/12433303/31548043-6e09e04c-b021-11e7-9922-7e201911e9f8.PNG)

the sum of 160.00 + 160.00 should be 320.00, as the quantity increases and new total is calculated, more pennies are missing from the basket total

**Comment by YodasMyDad** [comment]
This is actually correct. It's to do with how VAT is calculated. 

https://www.kashflow.com/support/kb/vat-calculation-methods/

This is because it's % of the total and you round up pennies. 

133.33 x 2 = 266.66
266.66 + 20% = 319.99
