### ISSUE TITLE
Get product's specified filters

### ISSUE THREAD

**Issue by mothman1** [Merchello/Merchello#2055]
I've searched all over the web but couldnt find an answer, apologise if my question has been answered but never found by me.

I have number of products and about 30 filters. A product may specify one or many filters. Now, I want to display all products to online users and allow them to filter their product choices using the specified filters.

For example, ProductA is suitable for vegetarian as well as nuts allergic people, while ProductB is suitable for vegan and diary allergic people (this very simple example is for illustration only).

Now, on products list page I easily display all products and all previously added Filters. However, I find no way to link listed products to their relevant filters, for when a user selects a filter the relevant products will be highlighted.

**Comment by YodasMyDad** [comment]
Please post this question on our.umbraco in the Merchello forum. Thanks.

**Comment by ronaldbarendse** [comment]
@YodasMyDad This is a recurring question and there's currently (still) no answer how to get all (checked) filters for a specific product:
- https://our.umbraco.com/projects/collaboration/merchello/merchello/85744-getting-filter-values-for-specific-product
- https://our.umbraco.com/projects/collaboration/merchello/merchello/88942-filters-with-products

Having an issue open for this to track any progress seems legit to me 😉
