### ISSUE TITLE
Not sure if this is fixed or still recurring bug

### ISSUE THREAD

**Issue by Jemzz** [Merchello/Merchello#2056]
I was told that this error would be fixed in the next release, I just upgraded from merchello 2.5.0 to 2.6.0 but when trying to create/edit an address in backoffice I still got this error. I'm unsure weather its the upgrade done wrong or its still an unfixed bug
![capture - copy](https://user-images.githubusercontent.com/12433303/31558373-82707898-b044-11e7-8d8b-ce61ea1feb01.PNG)

still getting angular error "Form submission cancelled because form is not connected"

**Comment by YodasMyDad** [comment]
Can you clear your cache please as I cannot replicate on latest version.
