### ISSUE TITLE
Update Merchello Slug Creation To Use Umbraco Character Replacement

### ISSUE THREAD

**Issue by YodasMyDad** [Merchello/Merchello#2061]
Message from Merchello user

When i create product with Polish letters e.g. Ołówek -> merchello create product slug by deleting polish letters -> so url will be ...../owek - and it is not good formated for SEO.

so I added this lines to changing polish letters (generally diacritic marks) to latin like it is done in umbraco, before formating url slug:

```
foreach (var n in UmbracoConfig.For.UmbracoSettings().RequestHandler.CharCollection)
{
if (n.Char != "")
value = value.Replace(n.Char, n.Replacement);
}

```
I wrote more about that in this post: https://our.umbraco.org/projects/collaboration/merchello/merchello/88306-changing-diactric-marks-in-slug-product

**Comment by ronaldbarendse** [comment]
@YodasMyDad And this breaks when the no characters are specified, but the configuration element does, e.g. `<urlReplacing toAscii="try"/>`... See how the default characters are set: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Configuration/UmbracoSettings/RequestHandlerElement.cs.

Why not just use the build-in `ToUrlSegment()` exntension method?
