### ISSUE TITLE
SalesOverTimeReport Weekly Summary returns 0 if the invoice date includes a time

### ISSUE THREAD

**Issue by samgooch** [Merchello/Merchello#2063]
The SumInvoiceTotals() method on the InvoiceRepository is being passed a start date and end date with the same date. The time is set to 00:00:00. So therefore the SQL query does not find any invoices for that period. I can see there is some commented out code to add a day to the date. But I suppose this should be passed in rather than modified at this level.

**Comment by samgooch** [comment]
I think the issue is on line 183 of the SalesOverTimeReportApiController

**Comment by YodasMyDad** [comment]
Assuming this is part of the PR you did?

**Comment by samgooch** [comment]
I have raised a different PR for this one - https://github.com/Merchello/Merchello/pull/2092
