### ISSUE TITLE
Weekly Sales Report totals seems to show the value for the previous day

### ISSUE THREAD

**Issue by samgooch** [Merchello/Merchello#2064]
The "This Week vs Last Week" report has the first day as "Saturday" and the total for that row seems to be the total for "Sunday". Having checked the code for the StartOfWeek() extension method it is returning Sunday. So it seems as if the angular view is showing the wrong day?

**Comment by YodasMyDad** [comment]
Again, assuming this is the PR you sent?

**Comment by samgooch** [comment]
Yes, the PR has now fixed this issue
