### ISSUE TITLE
Report SumInvoiceTotals include invoice status' other than Paid

### ISSUE THREAD

**Issue by samgooch** [Merchello/Merchello#2065]
Should the SumInvoiceTotals() method include all invoice status'? The report for "Sales" is misleading when this is the case?

**Comment by YodasMyDad** [comment]
Are you saying it does include all status? Or is only including some?

**Comment by samgooch** [comment]
Currently it includes all statuses. It would be nice to be able to choose on the Report page which statuses you want a report of. As I imagine, cancelled, unpaid, partial invoices may skew a lot of peoples reports.

**Comment by samgooch** [comment]
Fixed as part of https://github.com/Merchello/Merchello/pull/2226
