### ISSUE TITLE
ShipmentService.Created event

### ISSUE THREAD

**Issue by samgooch** [Merchello/Merchello#2066]
Is it possible to have a Created event for the shipment service?

I have an event hooked up to the "StatusChanged" event, however if the shop user fulfils an order and sets the status straight to "Shipped" or "Delivered" then this event does not fire. Therefore the notification email does not fire.

I'm a bit reluctant to do it on the Save event as this event could be fired for any form of update e.g. carrier. So the customer may receive multiple emails.

If I'm doing the notification wrong then just let me know :)

**Comment by YodasMyDad** [comment]
The event triggers from the shipment page/tab. So when set to shipped from the Shipments tab then. I have a site that sends an email when a shipment is shipped via the notifications, so I know it's working. It's more about processes, this bit really. The process is check the order, create the shipments and set to packaged. So you can see what shipments you have in the back office and set to shipped from there.
