### ISSUE TITLE
Unavailable products are included in the filter groups and the TotalItems count for a search

### ISSUE THREAD

**Issue by samgooch** [Merchello/Merchello#2071]
The product search is pulling back all available items. However, the TotalItems count is the count as if it was available and unavailable products.

This also happens for the filter groups and their counts.

**Comment by samgooch** [comment]
They are also returned in the ProductContentQuery search. But when accessing the item using the Merchello Helper's TypedProductContent() method it returns null.

**Comment by arknu** [comment]
I'm working on a PR for this, should be ready sometime this week.

**Comment by arknu** [comment]
PR here: https://github.com/Merchello/Merchello/pull/2179

**Comment by YodasMyDad** [comment]
Fixed in PR
