### ISSUE TITLE
ExtendedData Items as empty array causes CustomerDisplay model to be null

### ISSUE THREAD

**Issue by paradela** [Merchello/Merchello#2082]
https://github.com/Merchello/Merchello/blob/61baa3e230eaf24f54692e61186a7c509521d510/src/Merchello.FastTrack.Ui/App_Plugins/Merchello/js/merchello.models.js#L162

Hi Guys.

I've noticed that when using the customer backoffice I couldn't create or update any customers.
When I started digging I've discovered that the actions AddCustomer and PutCustomer in the CustomerApiController were receiving a null CustomerDisplay.

After some more research I've found that the reason was de ExtendedDataCollection object that was not being correctly deserialized.

When I tried in postman with the extendedData.Items = null it didn't threw any exception.

I've observed this issue in version 2.50 and in the 2.3.0, althought in 2.3.0 some installations ran without problem.

**Comment by YodasMyDad** [comment]
How and when do you get this? It should have been fixed in 2.5+?

**Comment by paradela** [comment]
Well I have this problem everytime when creating a customer or updating (add a new address) in every environment (development and QA) and also running locally.

Here's a print screen:

![image](https://user-images.githubusercontent.com/3149524/32135058-8053faf0-bbf0-11e7-93d5-e34bb0cc8475.png)

This is the request's body content:

`{"firstName":"Ricardo","key":"","lastActivityDate":"","lastName":"Paradela","loginName":"test@gmail.com","notes":[],"email":"test@gmail.com","taxExempt":false,"extendedData":{"items":[]},"addresses":[],"invoices":[]}`

**Comment by YodasMyDad** [comment]
I'm running a 2.7 alpha build and can't replicate this in it, so I'm closing for now.
