### ISSUE TITLE
Report Not working properly, (This week vs Last week)

### ISSUE THREAD

**Issue by Jemzz** [Merchello/Merchello#2115]
I have noticed that the report only shows sales from the current day you are in, the sales from yesterday is completely empty, then tommorow sales from today will be wiped from the "this week vs last week" report and only tomorrows sales are shown

![capture](https://user-images.githubusercontent.com/12433303/34203271-66b09238-e572-11e7-9018-adcb21496e54.PNG)

This image shows Thursdays sales, but there were sales yesterday and those have somehow been removed today and then tommorow the same thing, sales from Thursday will be removed and only friday sales will be shown. I'm not sure whats going on

Thank you

**Comment by samgooch** [comment]
Did you get a fix for this?

**Comment by YodasMyDad** [comment]
Fixed in v2.7.0
