### ISSUE TITLE
Unable to install with Umbraco 7.7.8

### ISSUE THREAD

**Issue by JesusAlbornoz** [Merchello/Merchello#2118]
Installation of Merchello 2.6.0 fails (using local install via zip) on umbraco 7.7.8.
This then also stops umbraco starting up correctly.
This is my TRACE LOG
`
2018-01-15 17:28:51,802 [P10292/D12/T1] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Exception (92ee0e74).
System.OverflowException: Value was either too large or too small for an Int32,
   en System.Convert.ToInt32(UInt64 value)
   en System.UInt64.System.IConvertible.ToInt32(IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType)
   en Umbraco.Core.Persistence.Database.ExecuteScalar[T](String sql, Object[] args)
 2018-01-15 17:28:51,805 [P10292/D12/T1] ERROR Merchello.Core.Persistence.Migrations.CoreMigrationManager - Merchello Database Schema Upgrade Failed
System.OverflowException: Value was either too large or too small for an Int32,.
   en System.Convert.ToInt32(UInt64 value)
   en System.UInt64.System.IConvertible.ToInt32(IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType)
   en Umbraco.Core.Persistence.Database.ExecuteScalar[T](String sql, Object[] args)
   en Umbraco.Core.Persistence.Database.ExecuteScalar[T](Sql sql)
   en Merchello.Core.Persistence.DatabaseExtensions.GetDbTableColumnSize(Database database, String tableName, String columnName)
   en Merchello.Core.Persistence.Migrations.Upgrades.TargetVersionTwoThreeOne.AlterProductAttributeColumnToNtext.Up()
   en Umbraco.Core.Persistence.Migrations.MigrationBase.GetUpExpressions(IMigrationContext context)
   en Merchello.Core.Persistence.Migrations.CoreMigrationManager.InitializeMigrations(List`1 migrations, Database database, DatabaseProviders databaseProvider, Boolean isUpgrade)
   en Merchello.Core.Persistence.Migrations.CoreMigrationManager.UpgradeMerchello(Database database)
 2018-01-15 17:28:51,808 [P10292/D12/T1] ERROR Umbraco.Core.CoreBootManager - An error occurred running OnApplicationStarted for handler Merchello.Web.UmbracoApplicationEventHandler
System.OverflowException: Value was either too large or too small for an Int32,.
   en System.Convert.ToInt32(UInt64 value)
   en System.UInt64.System.IConvertible.ToInt32(IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType)
   en Umbraco.Core.Persistence.Database.ExecuteScalar[T](String sql, Object[] args)
   en Umbraco.Core.Persistence.Database.ExecuteScalar[T](Sql sql)
   en Merchello.Core.Persistence.DatabaseExtensions.GetDbTableColumnSize(Database database, String tableName, String columnName)
   en Merchello.Core.Persistence.Migrations.Upgrades.TargetVersionTwoThreeOne.AlterProductAttributeColumnToNtext.Up()
   en Umbraco.Core.Persistence.Migrations.MigrationBase.GetUpExpressions(IMigrationContext context)
   en Merchello.Core.Persistence.Migrations.CoreMigrationManager.InitializeMigrations(List`1 migrations, Database database, DatabaseProviders databaseProvider, Boolean isUpgrade)
   en Merchello.Core.Persistence.Migrations.CoreMigrationManager.UpgradeMerchello(Database database)
   en Merchello.Core.Persistence.Migrations.CoreMigrationManager.EnsureMerchelloVersion()
   en Merchello.Web.UmbracoApplicationEventHandler.VerifyMerchelloVersion()
   en Merchello.Web.UmbracoApplicationEventHandler.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   en Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   en Umbraco.Core.CoreBootManager.<Complete>b__38_0(IApplicationEventHandler x)
 2018-01-15 17:28:51,813 [P10292/D12/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.OverflowException: Value was either too large or too small for an Int32,.
   en System.Convert.ToInt32(UInt64 value)
   en System.UInt64.System.IConvertible.ToInt32(IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType)
   en Umbraco.Core.Persistence.Database.ExecuteScalar[T](String sql, Object[] args)
   en Umbraco.Core.Persistence.Database.ExecuteScalar[T](Sql sql)
   en Merchello.Core.Persistence.DatabaseExtensions.GetDbTableColumnSize(Database database, String tableName, String columnName)
   en Merchello.Core.Persistence.Migrations.Upgrades.TargetVersionTwoThreeOne.AlterProductAttributeColumnToNtext.Up()
   en Umbraco.Core.Persistence.Migrations.MigrationBase.GetUpExpressions(IMigrationContext context)
   en Merchello.Core.Persistence.Migrations.CoreMigrationManager.InitializeMigrations(List`1 migrations, Database database, DatabaseProviders databaseProvider, Boolean isUpgrade)
   en Merchello.Core.Persistence.Migrations.CoreMigrationManager.UpgradeMerchello(Database database)
   en Merchello.Core.Persistence.Migrations.CoreMigrationManager.EnsureMerchelloVersion()
   en Merchello.Web.UmbracoApplicationEventHandler.VerifyMerchelloVersion()
   en Merchello.Web.UmbracoApplicationEventHandler.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   en Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   en Umbraco.Core.CoreBootManager.<Complete>b__38_0(IApplicationEventHandler x)
   en Umbraco.Core.EnumerableExtensions.ForEach[TItem](IEnumerable`1 items, Action`1 action)
   en Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   en Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
   en Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
   en Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e)
`

**Comment by dstream** [comment]
I can't install merchello even install via Umbraco package manager (umbraco 7.7.8 and 7.8.0), this is my trace log:

[UmbracoTraceLog.NGHIA-T440P.txt](https://github.com/Merchello/Merchello/files/1705577/UmbracoTraceLog.NGHIA-T440P.txt)

**Comment by geoffbeaumont** [comment]
I get a completely different error when trying to install Merchello (Merchello 7.6.0 from downloaded package zip).

The error I get is:
2018-02-13 15:04:01,850 [P20736/D2/T16] ERROR umbraco.cms.businesslogic.packager.Installer - Error importing file C:\Users\GeoffBeaumont\Projects\DPC\FamilyQuilt\FamilyQuilt\App_Data\f8a85616-3226-41f4-a1cd-bc3d2f713599.umb
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\GeoffBeaumont\Projects\DPC\Soln\Project\App_Data\f8a85616-3226-41f4-a1cd-bc3d2f713599\1c953165-05f0-4f5d-8779-4d396a172259.manifest'.

The really weird thing here is that the package is successfully extracted and the license agreement shown, but as soon as installation is confirmed the entire f8a85616-3226-41f4-a1cd-bc3d2f713599 (or whichever has been generated on that attempt) is deleted - you can watch the files disappear in windows explorer! So the error that follows is quite correct - the manifest file is gone...

**Comment by geoffbeaumont** [comment]
As an aside - I know there's a NuGet package of the core binaries. But a proper NuGet installation package would be a lot less painful from a development point of view.

**Comment by rustyswayne** [comment]
@geoffbeaumont Agreed a proper NuGet package would be nice but the installer relies on certain package actions at this point.

**Comment by rustyswayne** [comment]
@JesusAlbornoz your log file suggests you are trying to install the FastTrack starter package without first installing the Merchello package.  Is that the case?

**Comment by geoffbeaumont** [comment]
@rustyswayne it looks like the issue I'm seeing is this one http://issues.umbraco.org/issue/U4-9297 - so it's an Umbraco bug not a Merchello one. And a bit of a weird one too - seems to happen on some installs but not others!

**Comment by geoffbeaumont** [comment]
I can confirm that the workaround in U4-9297 works for me (delete the package folder before clicking the install button). So it's definitely the same issue.

**Comment by coenvc** [comment]
Having the same issue. This is my log, removing the package folder before clicking the install button didn't work for me

[OverflowException: De waarde is te groot of te klein voor een Int32.]    System.Convert.ToInt32(UInt64 value) +6306924    System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) +568    Umbraco.Core.Persistence.Database.ExecuteScalar(String sql, Object[] args) +403    Merchello.Core.Persistence.Migrations.Upgrades.TargetVersionTwoThreeOne.AlterProductAttributeColumnToNtext.Up() +247    Merchello.Core.Persistence.Migrations.CoreMigrationManager.InitializeMigrations(List`1 migrations, Database database, DatabaseProviders databaseProvider, Boolean isUpgrade) +202    Merchello.Core.Persistence.Migrations.CoreMigrationManager.UpgradeMerchello(Database database) +1365    Merchello.Core.Persistence.Migrations.CoreMigrationManager.EnsureMerchelloVersion() +188    Merchello.Web.UmbracoApplicationEventHandler.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) +905    Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) +50    Umbraco.Core.CoreBootManager.<Complete>b__38_0(IApplicationEventHandler x) +381    Umbraco.Core.EnumerableExtensions.ForEach(IEnumerable`1 items, Action`1 action) +166    Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete) +416    Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete) +136    Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e) +381  [HttpException (0x80004005): De waarde is te groot of te klein voor een Int32.]    System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +521    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +185    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +418    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369  [HttpException (0x80004005): De waarde is te groot of te klein voor een Int32.]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +534    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +718
--

**Comment by geoffbeaumont** [comment]
@coenvc looks like you have the same problem as @JesusAlbornoz, which @rustyswayne said was down to trying to install the FastTrack package without installing the main Merchello package first.

**Comment by coenvc** [comment]
@geoffbeaumont  I am trying too install this zip file, for as far as I am aware this is Merchello without Fasttrack
[Merchello_2.6.0.zip](https://github.com/Merchello/Merchello/files/1749431/Merchello_2.6.0.zip)'

**Comment by geoffbeaumont** [comment]
@coenvc - yep, that's the core Merchello. It's not what I suggested the problem was then!

**Comment by MvG013** [comment]
I have the same issue as @coenvc & @JesusAlbornoz. After installing merchello i get an overflowexception of an int being to big or to small for an Int32...  Anyone knows a solution ?

**Comment by iand123** [comment]
I think i know what the problem is with this as i just had it. 

I installed merchello and then the umbraco back end wouldnt work. Looking at the error in the code it was related to this migration

https://github.com/Merchello/Merchello/blob/f3dd636fb3449d58d82ecd178b2ce9b1093c9615/src/Merchello.Core/Persistence/Migrations/Upgrades/TargetVersionTwoThreeZero/AlterAppliedPaymentDescriptionFieldSize.cs

It is trying to convert a field to NTEXT which doesnt exist in SQL Server. The field was previously LONGTEXT which is an equivalent.

To fix it it i changed the following in the database

Table: merchproductattribute

Field: detachedContentValues to be a VARCHAR(1000)

The migration had a check for the field size being over 500 and if so thinks the migration has already happened and therefore continues. This now makes the umbraco backend load

Can someone who knows the code better comment on the impact of this elsewhere in the code and also how the product will behave?

**Comment by YodasMyDad** [comment]
If it is this issue, changing it to a varchar will be fine as far as I am aware, however if it's for the detachedContentValues then it will need to be varchar(max) as detachedContentValues could be a very large JSON string.

**Comment by YodasMyDad** [comment]
Will fully test v2.7.0 install

**Comment by ruant** [comment]
So what was the solution for this problem?
Or is this a problem because I'm doing a new db installation with my current ("old") code where Merchello already is added?
