### ISSUE TITLE
Merchello.TestsBase nuget package referencing wrong depency name?

### ISSUE THREAD

**Issue by kedde** [Merchello/Merchello#2127]
I'm not able to install merchello test, I suspect the dependency name should be umbracocms.core and not umbraco.core

[see line](https://github.com/Merchello/Merchello/blob/merchello-dev/build/NuSpec/Merchello.TestsBase.nuspec#L19)

Btw, is the dependencies needed? If I have a test in another project it would install both the umbraco core and the braintree package?

**Comment by rustyswayne** [comment]
@kedde The dependency reference in the nuspec file is the issue.  The tests need attention (reworking).  To answer your question, it would install both packages.  What are you trying to test?

**Comment by rustyswayne** [comment]
Fixed in https://github.com/Merchello/Merchello/pull/2128

**Comment by kedde** [comment]
Hi

Thanks for the fix. 

I was trying to test a custom payment provider and method, I'm using Umbraco As A Service and I have a separate test project that have references to the "core-dll's" in the Umbraco As A Service project. When installing the Merchello-test-package my references will now point to the new dll's in the packages directory. It's not a big issue I'll just create a separate solution for my payment provider.
