### ISSUE TITLE
How to upgrade to latest version from GitHub Repository?

### ISSUE THREAD

**Issue by JohnBergman** [Merchello/Merchello#2135]
After installing the package from our.umbraoc.com, I noticed that there were a few things that have been committed into the source code repo that would be useful to have.

Is there documentation about how to "convert" a normally installed instance to one that includes the latest changes from GitHub? I looked at the source code, and noted that there were several projects that are not to be built; so the overall integration of this is a bit confusing to me as to exactly what the best way is to accomplish this.

**Comment by Vrijdagonline** [comment]
Would be great to have a new release. Especially the Cache-Busting commit is one that @YodasMyDad  did a great job with. As I think that will fix many issues like losing address information for registered customers on the frontend.

Maybe @YodasMyDad has an idea when this 2.7.0 will be released?

Cheers,
Arjan

**Comment by YodasMyDad** [comment]
Will try and get v2.7.0 out before xmas

**Comment by Vrijdagonline** [comment]
That is awesome to hear Lee! Thank you!
