### ISSUE TITLE
CreateDate and UpdateDate always have DateMinvalue

### ISSUE THREAD

**Issue by Vrijdagonline** [Merchello/Merchello#2137]
Hi,

Product Sorting on createdate and updatedate is not possible, because these values always have a datetime.minvalue .

**Comment by chrno1209** [comment]
I have the same issue, do you have any workaround?

**Comment by Vrijdagonline** [comment]
I skipped the implementation of this feature. So I can't help you with a workaround. I would like to know how to fix this too, so if you find something, please share.

**Comment by chrno1209** [comment]
I am skipping this too, leaving the time to finish the project first, and then get back to fix this.
My first thought is to catch event when Merchello is saving product into db, then modify CreatedDate and UpdateDate, but not sure if it works or not.
Will keep you posted on this :).

**Comment by YodasMyDad** [comment]
I would highly suspect this is an examine date conversion issue. As the createDate and the updateDate are stored in the database correctly.

**Comment by Vrijdagonline** [comment]
@YodasMyDad You are right. I came to the same conclusion back then. But couldn't find where the values gets lost exactly.

**Comment by YodasMyDad** [comment]
Just looking into this a bit more. Where exactly are you sorting? As there is no date sorting in the back office? And where are you seeing the minvale dates?

**Comment by YodasMyDad** [comment]
This is now fixed in https://github.com/Merchello/Merchello/pull/2186

**Comment by Vrijdagonline** [comment]
Cool! 👍
