### ISSUE TITLE
SortBy Price

### ISSUE THREAD

**Issue by stefano-skemalog** [Merchello/Merchello#2138]
Hi all,
any of search product functions can sort result by price.
I need to sort result by saleprice, how can I do this?

Thank you
Stefano

**Comment by cwbrandsdal** [comment]
Something like this?

    var merchello = new MerchelloHelper();

    var searchTerm = Request.QueryString["q"];

    var productQuery = merchello.Query.Product;
    var result = productQuery.Search(searchTerm, 1, long.MaxValue);

    var allProducts = Merchello.ProductContentQuery().Execute().Items.OrderBy(p => p.Price);

**Comment by stefano-skemalog** [comment]
I was referring to the functions with paged results.
However I have implemented the feature and submitted to pull requests.
