### ISSUE TITLE
Deleting products not working as desired

### ISSUE THREAD

**Issue by kgiszewski** [Merchello/Merchello#2143]
- Installed Fast Track
- Tried to remove all the T-Shirts

![image](https://user-images.githubusercontent.com/4653907/37841137-4f870ea4-2e95-11e8-8da3-b489a936799d.png)

UI doesn't respond when clicking `Delete` nor does the T-Shirt delete. Seems I have to do so individually.

No JS errors.

**Comment by kgiszewski** [comment]
Merch - `v2.6.0` 
Umb - `v7.7.13`

Products are now gone, but can't remove T-Shirt types nor T-Shirt node.

**Comment by Vrijdagonline** [comment]
Hi Kevin, this has already been solved in the upcoming 2.7.0 release. 
If you need a quick fix:
https://github.com/Merchello/Merchello/pull/2045/files

Cheers,
Arjan

**Comment by kgiszewski** [comment]
Woohoo!
