### ISSUE TITLE
Adding several Product Content Types in Content Types tab pushes the Product Option Content Types section off the page

### ISSUE THREAD

**Issue by dclinton182** [Merchello/Merchello#2146]
If you had say 6 or 7 entries to the Product Content Types section it pushes the content off the page so you can't click the "Add" button on the "Product Option Content Types" section below.

Adding "overflow-y: auto;" to the parent ".umb-panel tabbable" div fixes it for me locally but there's probably a better way to solve it :)

**Comment by YodasMyDad** [comment]
Just needs the view updating as missing the merchello panel wrappers
