### ISSUE TITLE
Deleting a shipping method from the shipping provider causes error

### ISSUE THREAD

**Issue by geoffbeaumont** [Merchello/Merchello#2154]
When we delete a shipping method from a country, we're then getting a 500 error from the handler that provides the countries/shipping methods to the admin screen.

The message returned from the handler says it is unable to serialize data, but the underlying issue is that it can't open a command as it's already open. The only fix is to recycle the app pool. All users are affected, so it isn't session based.

This is reliably reproducable - every time a shipping method is deleted.

Merchello 2.6 / Umbraco 7.7.9

**Comment by YodasMyDad** [comment]
Should be fixed in 2.7 as a load of the over the top caching ripped out
