### ISSUE TITLE
Can't delete Collection.

### ISSUE THREAD

**Issue by eriksimonic** [Merchello/Merchello#2155]
Hi.
I have installed FastTrac 2.6 on a fresh installation of Umbraco 7.10.4. As far I know only deleting a collection through backend does not work. I tried to debug the controller, 
Angular
Merchello.EntityCollections.Dialogs.DeleteEntityCollectionController

The event does not fire when the button is clicked.
![collection delete bug](https://user-images.githubusercontent.com/10416737/39696845-51a3ee64-51ef-11e8-96fa-3540d1b8e375.gif)

Regards.

**Comment by InvalidHandle** [comment]
That's because clicking the delete button tries to execute the "save" function instead of "confirmDelete", you can fix it yourself for now [https://our.umbraco.org/projects/collaboration/merchello/merchello/88717-cant-delete-collection](url)

**Comment by YodasMyDad** [comment]
Fixed in 2.7
