### ISSUE TITLE
v2.7 beta error when installing on umb v7.11.1

### ISSUE THREAD

**Issue by LottePitcher** [Merchello/Merchello#2169]
Here's the section of the log from the first mention of Merchello:

[tracelog-merchello-error.txt](https://github.com/Merchello/Merchello/files/2188868/tracelog-merchello-error.txt)

**Comment by YodasMyDad** [comment]
Thanks. Was this using SQL Express or SQLCE?

**Comment by LottePitcher** [comment]
SQL express (2012).  I had a done clean install of latest umbraco, with starter kit, then installed merchello package via back office.

On 13 Jul 2018, at 06:15, Lee <notifications@github.com> wrote:

Thanks. Was this using SQL Express or SQLCE?

**Comment by kdemanuele** [comment]
Tried to install the package on Umbraco 7.11.1, fresh install with no start kit, using both SQLCE and SQL Server 2017 Developer. In both cases have received the same error as reported by LottePitcher.

The original error looks to be
```
[TypeInitializationException: The type initializer for 'Merchello.Core.Configuration.MerchelloVersion' threw an exception.]
   Merchello.Core.Configuration.MerchelloVersion.get_Current() +14
   Merchello.Core.Persistence.Migrations.CoreMigrationManager.EnsureMerchelloVersion() +40
   Merchello.Web.UmbracoApplicationEventHandler.VerifyMerchelloVersion() +128
   Merchello.Web.UmbracoApplicationEventHandler.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) +801
```

**Comment by YodasMyDad** [comment]
All working now. Will release soon
