### ISSUE TITLE
Braintree environmentType not updating after changing environment credentials

### ISSUE THREAD

**Issue by danbramall** [Merchello/Merchello#2170]
Hi,

We just changed from Sandbox to Production mode to put through a test live transaction via the Braintree provider in Merchello 2.5.0. After changing API credentials in the Merchello UI (which seemed to save correctly as far as the UI is concerned) we started receiving an error "Failed to retrieve and/or create a Braintree Customer" when the hosted fields form was rendered out to the payment page on the front-end of the site.

Digging into it, and helpfully finding [this post on 'Our'](https://our.umbraco.com/projects/collaboration/merchello/merchello/80067-brain-tree-payments-token-issue) it became apparent that the 'environmentType' setting in the 'extendedData' field of the 'merchGatewayProviderSettings' database table was still showing as 'Sandbox'.  Changing this to 'Production' and restarting the App Pool resulted in successful rendering of the payment form in production mode.

**Comment by YodasMyDad** [comment]
Fixed in 2.7
