### ISSUE TITLE
Umbraco 8?

### ISSUE THREAD

**Issue by ruant** [Merchello/Merchello#2235]
Has there been any work done on this?
Or will it just work?

**Comment by medarke** [comment]
I would like to know the answer to this too

**Comment by YodasMyDad** [comment]
Currently there are no plans to update Merchello on v8.

**Comment by ruant** [comment]
Okay.. That's weird.

https://merchello.com/faqs/
`Will Merchello work with v8 of Umbraco?`
`Yes, we are already working on v8 support for Merchello.`

**Comment by protherj** [comment]
My guess is that some community members could give it a go and add specific issues that need to be resolved in the issue tracker.  Then perhaps everyone could pitch in and go through the list?

**Comment by YodasMyDad** [comment]
That was when v8 started to be developed, it didn't look like too much was changing but A LOT has changed. One of the mistakes made with Merchello is that it's too tightly coupled with Umbraco which means a lot will need changing I suspect. Currently I do not have the time, or the need to update it to v8 as the stores I have run perfectly fine on v7 (If it ain't broke and all that).

**Comment by benjaminhowarth1** [comment]
@YodasMyDad Do you mind if I take a punt at this?

**Comment by biapar** [comment]
Any news?

**Comment by ruant** [comment]
@biapar Check the readme file

`Merchello is a highly configurable, open source eCommerce package for Umbraco CMS v7 ONLY. However, this project is no longer actively developed.`

**Comment by biapar** [comment]
So, Is't very hard to porto to 8?

**Comment by benjaminhowarth1** [comment]
Yes, very difficult - I'm working on this effort.

**Comment by biapar** [comment]
How can I help?

**Comment by benjaminhowarth1** [comment]
@biapar I've created a fork over here where I'm working on the "develop" branch: https://github.com/benjaminhowarth1/Merchello. I'll set up some issues in a project to be opened up & then we can liaise on what the priorities are?

**Comment by biapar** [comment]
with new free Github plan, you can.
