### ISSUE TITLE
Enhancement Request: Add a Stripe Gateway Payment Provider

### ISSUE THREAD

**Issue by John-Blair** [Merchello/Merchello#2252]
Stripe transaction costs are cheaper than Braintree and Paypal and would be a benefit to a lot of merchello merchants.

Stripe:  3.4% on a £10 sale.
https://stripe.com/en-GB/pricing

Braintree:  more expensive: 3.9% on a £10 sale.
https://www.braintreepayments.com/gb/braintree-pricing

Paypal - very expensive: 5.4% on a £10 sale.
https://www.paypal.com/uk/webapps/mpp/paypal-fees

<kbd>[Enhancement Request ]</kbd>

**Comment by benjaminhowarth1** [comment]
You can find a community-supported Stripe payment provider here: https://github.com/alindgren/MerchelloStripeProvider

**Comment by John-Blair** [comment]
Thank you for the lightning quick response !

**Comment by benjaminhowarth1** [comment]
Both Braintree and Paypal will be moved to "optional" Nuget packages in the forthcoming 2.7.1 release, once I've finished tidying up the Angular code for each of them, and I'll then be looking to update the Stripe provider as well.

The TL;DR is that Merchello.Core currently has hard dependencies on the Braintree & Paypal SDKs.
This is bad for the Stripe & other third-party payment gateway providers. So, abstracting the providers out into their own Nuget projects will add some sensibility to the dependency tree.

Related ticket, pull requests, and comments can be found here: https://github.com/Merchello/Merchello/issues/2239
