### ISSUE TITLE
Received an error from server

### ISSUE THREAD

**Issue by rashedhumayun2k3** [Merchello/Merchello#2289]
Hi,
I am stuck with this problem from 5 days. Please help me. 

 I am getting error while I click in Merchello "Sales" button. The error is Received an error from server. 
I read the log file and got something like that:
 ERROR Merchello.Web.Editors.InvoiceApiController - Unhandled controller exception occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: indexProvider
   at Merchello.Core.Ensure.That[TException](Boolean condition, Func`1 defer)
   at Merchello.Core.Ensure.ParameterNotNull[T](T value, String paramName)
   at Merchello.Web.Search.CachedQueryBase`2..ctor(CacheHelper cacheHelper, IPageCachedService`1 service, BaseIndexProvider indexProvider, BaseSearchProvider searchProvider, Boolean enableDataModifiers)
   at Merchello.Web.Search.CachedOrderQuery..ctor(IMerchelloContext merchelloContext, BaseIndexProvider indexProvider, BaseSearchProvider searchProvider, Boolean enableDataModifiers)
   at Merchello.Web.Search.CachedOrderQuery..ctor(IMerchelloContext merchelloContext, Boolean enableDataModifiers)
   at Merchello.Web.Search.CachedInvoiceQuery..ctor(IMerchelloContext merchelloContext, Boolean enableDataModifiers)
   at Merchello.Web.Search.CachedQueryProvider.<>c__DisplayClass4.<InitializeProvider>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Merchello.Web.Search.CachedQueryProvider.get_Invoice()
   at Merchello.Web.Editors.InvoiceApiController.SearchInvoices(QueryDisplay query)
   at lambda_method(Closure , Object , Object[] )

**Comment by chrno1209** [comment]
This is something relate to the index I assume.
My suggestion is:
1. Go to Developer -> Examine Management, there are 4 Merchello indexers over there, try to reindex all again
![image](https://user-images.githubusercontent.com/4859745/65875471-8e710980-e3b1-11e9-84ec-56a6b7f24816.png)

2. If above solution does not work, try to delete all index data in App_Data then restart IIS again.

Good luck :)

**Comment by rashedhumayun2k3** [comment]
Thanks for response.
I am getting only few indexer but not the MerchelloCustomerIndexer, MerchelloInvoiceIndexer, MerchelloOrderIndexer, MerchelloProductIndexer in my project.


In my application I have the following indexer:
ExternalIndexer
InternalIndexer
InternalMemberIndexerc

I am totally new in umbraco, learning day by day. I am very happy that you people are very helpful.

**Comment by chrno1209** [comment]
When installing Merchello, it will also install it's indexers, including MerchelloProductIndexer, MerchelloInvoiceIndexer, MerchelloOrderIndexer and MerchelloCustomerIndexer.
If for some reason Merchello didn't install correctly, there might be more errors, but if it's just the indexers, then you can modify the examine settings instead of reinstall Merchello again.

1. Edit config/ExamineIndex.config, add these lines:
```
  <IndexSet SetName="MerchelloProductIndexSet" IndexPath="~/App_Data/TEMP/ExamineIndexes/{machinename}/Merchello/Product/" />
  <IndexSet SetName="MerchelloInvoiceIndexSet" IndexPath="~/App_Data/TEMP/ExamineIndexes/{machinename}/Merchello/Invoice/" />
  <IndexSet SetName="MerchelloOrderIndexSet" IndexPath="~/App_Data/TEMP/ExamineIndexes/{machinename}/Merchello/Order/" />
  <IndexSet SetName="MerchelloCustomerIndexSet" IndexPath="~/App_Data/TEMP/ExamineIndexes/{machinename}/Merchello/Customer/" />
```
2. Edit config/ExamineSettings.config, add these lines in corresponding node
```
<Examine>
  <ExamineIndexProviders>
    <providers>
      ...
      <add name="MerchelloProductIndexer" type="Merchello.Examine.Providers.ProductIndexer, Merchello.Examine" />
      <add name="MerchelloInvoiceIndexer" type="Merchello.Examine.Providers.InvoiceIndexer, Merchello.Examine" />
      <add name="MerchelloOrderIndexer" type="Merchello.Examine.Providers.OrderIndexer, Merchello.Examine" />
      <add name="MerchelloCustomerIndexer" type="Merchello.Examine.Providers.CustomerIndexer, Merchello.Examine" />
    </providers>
  </ExamineIndexProviders>
  <ExamineSearchProviders defaultProvider="ExternalSearcher">
    <providers>
      ...
      <add name="MerchelloProductSearcher" type="Examine.LuceneEngine.Providers.LuceneSearcher, Examine" />
      <add name="MerchelloInvoiceSearcher" type="Examine.LuceneEngine.Providers.LuceneSearcher, Examine" />
      <add name="MerchelloOrderSearcher" type="Examine.LuceneEngine.Providers.LuceneSearcher, Examine" />
      <add name="MerchelloCustomerSearcher" type="Examine.LuceneEngine.Providers.LuceneSearcher, Examine" />
    </providers>
  </ExamineSearchProviders>
</Examine>
```

**Comment by YodasMyDad** [comment]
Firstly, what version of Umbraco are you using? Merchello will not work with v8. Secondly, what package did you install and where from?

**Comment by rashedhumayun2k3** [comment]
Hi Chrno,
Many many thanks to you.
Its working now after adding those settings in config files.

Thanks

**Comment by chrno1209** [comment]
Glad that it works :)
Cheers

**Comment by sumoncuet** [comment]
Hello I'm new in umbraco. after installing merchello, I'm getting this error when click on catalog. Can u help me plz?
![catalog error](https://user-images.githubusercontent.com/1089392/66022500-02c1bf00-e510-11e9-9960-30e868c36691.PNG)

**Comment by chrno1209** [comment]
can you check log and provide error detail?

**Comment by sumoncuet** [comment]
![catalog error 2](https://user-images.githubusercontent.com/1089392/66023792-0a836280-e514-11e9-8b4b-61604c3c19d1.PNG)

**Comment by chrno1209** [comment]
You need to check the full log files generated by log4net in App_Data which provide more useful error detail than the browser console.

**Comment by sumoncuet** [comment]
Yes, The following things I got in log file
 2019-10-02 13:14:06,507 [P2044/D8/T38] ERROR Merchello.Web.Editors.EntityCollectionApiController - Unhandled controller exception occurred
System.NullReferenceException: EntityCollection does not exist

**Comment by chrno1209** [comment]
The message itself does tell you the issue, which the collection does not exist any more.
