### ISSUE TITLE
Can old contents of merchAnonymousCustomer and merchItemCache be deleted?

### ISSUE THREAD

**Issue by lesley-w** [Merchello/Merchello#2367]
We've noticed that the merchAnonymousCustomer and merchItemCache tables for one of our clients both have ~ 4 million records, even though there have been less than 10,000 invoices created during the same period.

Is it safe to delete old records from these tables?

**Comment by YodasMyDad** [comment]
Yes. For merchAnonymousCustomer. I have a manual task that runs once a day.

        /// <summary>
        ///     Clears the annonomous customers in the site
        /// </summary>
        internal void RemoveAnonymousCustomers()
        {
            // We delete any anonomous customers from over 30 days ago
            var dateThirdyDaysAgo = DateTime.Today.AddDays(-30);

            try
            {
                const string query = "DELETE FROM merchAnonymousCustomer WHERE [merchAnonymousCustomer].[createDate] <= @date";
                var constr = ConfigurationManager.ConnectionStrings["umbracoDbDSN"].ConnectionString;
                using (var con = new SqlConnection(constr))
                {
                    using (var cmd = new SqlCommand(query))
                    {
                        cmd.Parameters.AddWithValue("@date", dateThirdyDaysAgo);
                        cmd.Connection = con;
                        con.Open();
                        cmd.ExecuteNonQuery();
                        con.Close();
                    }
                }

                LogHelper.Warn(typeof(RecurringTasksService),
                    $"Deleting anonymous customers older than {dateThirdyDaysAgo:dd-MM-yyyy}");
            }
            catch (Exception ex)
            {
                LogHelper.Error<RecurringTasksService>(
                    $"Error deleting anonymous customers older than {dateThirdyDaysAgo:dd-MM-yyyy}", ex);
            }
        }
